fallen_tree = {}
fallen_tree2 = {}
tree1 = {}
tree2 = {}
tree3 = {}
tree4 = {}
tree5 = {}
tree6 = {}
tree7 = {}
tree8 = {}
tree9 = {}
tree10 = {}
tree11 = {}
tree12 = {}
tree13 = {}
tree14 = {}
tree15 = {}
tree16 = {}
tree17 = {}
tree18 = {}
tree19 = {}
tree20 = {}
coal1 = {}
coal2 = {}
coal3 = {}
coal4 = {}
coal5 = {}
andesite_vein = {}
diorite1 = {}
diorite2 = {}
diorite3 = {}
granite_vein = {}
granite_vein2 = {}
granite_vein3 = {}
iron1 = {}
iron2 = {}
iron3 = {}
iron4 = {}
iron5 = {}
iron6 = {}
iron7 = {}
iron8 = {}
iron9 = {}
iron10 = {}
iron11 = {}
