fallen_tree = {}
fallen_tree2 = {}
tree1 = {}
tree2 = {}
tree3 = {}
tree4 = {}
tree5 = {}
tree6 = {}
tree7 = {}
tree8 = {}
tree9 = {}
tree10 = {}
tree11 = {}
tree12 = {}
tree13 = {}
tree14 = {}
tree15 = {}
tree16 = {}
tree17 = {}
tree18 = {}
tree19 = {}
tree20 = {}
